### ISSUE TITLE
ADD feature that if the item has certain lore it will increase the chance for loot

### ISSUE THREAD

**Issue by SnUncle** [Rosewood-Development/RoseLoot#11]
Like if i have '12312 %player_name%' on my item i will get more loots from killing zombie

**Comment by Esophose** [comment]
It's should be possible to do this using the [CheckItem PlaceholderAPI expansion](https://github.com/PlaceholderAPI/CheckItem-Expansion). I'm not exactly sure how to use the plugin myself though. I think it would be something like `placeholder:%checkitem_lorecontains:12312 %player%%=yes` for the RoseLoot condition which would check if the item the player is holding contains .
