### ISSUE TITLE
[SUGGESTIONS] Override spawner conditions

### ISSUE THREAD

**Issue by introvertism** [Rosewood-Development/RoseLoot#12]
I think it would be a nice feature to be able to override spawn conditions of specified mobs, for example making it so pigs don't need grass in order to spawn, or making it so iron golems/etc can spawn in mid air. Some other plugins have a similar feature and I'd love to see it here.

**Comment by introvertism** [comment]
I posted this on the wrong repository... sorry.

**Comment by Esophose** [comment]
Before you go and post this in RoseStacker, that's already possible. Check the spawner_settings.yml file!
