### ISSUE TITLE
Disable some events

### ISSUE THREAD

**Issue by WarnDa** [Rosewood-Development/RoseLoot#18]
Hello,
I'm using this plugin only to edit fishing drops, but it's listening to events from block and entity, so it's taking 1% server performances !
It would be possible to add config option to disable theses event, or detect which lootables are usable and disable events of non used lootables ?
![image](https://github.com/Rosewood-Development/RoseLoot/assets/31826333/6bb268a1-b710-4b42-b43d-5c6100549fc7)

**Comment by Esophose** [comment]
I'll get that resolved when I'm next available

**Comment by WarnDa** [comment]
> I'll get that resolved when I'm next available

Just updated to 1.1.20, and it's the same as before : 
![image](https://github.com/Rosewood-Development/RoseLoot/assets/31826333/fff760a3-2aa4-4231-b676-d70001154e1e)

**Comment by WarnDa** [comment]
Hello,
Thanks it's fine in latest dev build !
![image](https://github.com/Rosewood-Development/RoseLoot/assets/31826333/f52f1b99-01f9-4bef-8da3-99c95eb7bad3)
