### ISSUE TITLE
[Feature Request] Condition of naturally generated blocks

### ISSUE THREAD

**Issue by WsJohn** [Rosewood-Development/RoseLoot#23]
I believe this is a very common condition; otherwise, players will satisfy specific conditions by placing blocks to get more rewards. Please add this condition.

**Comment by Esophose** [comment]
It isn't really possible to add a condition like that without tracking every block broken and placed in the world. As such, we only offer the condition in the form of a CoreProtect hook. This performs database queries on the main thread and can slow down your server, so it is not recommended except for rare drops. The condition is `coreprotect-natural-block` with no parameters.

**Comment by WsJohn** [comment]
Thats enough for me, thanks for your reply.(so fast
