### ISSUE TITLE
Is it possible to add support for this plugin ?

### ISSUE THREAD

**Issue by HoneyBearc** [Rosewood-Development/RoseLoot#27]
[NeigeItems github](https://github.com/ankhorg/NeigeItems-Kotlin)
example:
type: ENTITY
overwrite-existing: items
conditions:
  - 'entity-type:villager'
pools:
  0:
    conditions: []
    rolls: 1
    bonus-rolls: 0
    entries:
      0:
        conditions: []
        items:
          0:
            type: custom_item
            plugin: neigeitems
            item: 'ExampleItem1'
            amount: 1

**Comment by Esophose** [comment]
I'll look into adding this soon

**Comment by HoneyBearc** [comment]
If it can be added, I am willing to pay the addition fee.

**Comment by Esophose** [comment]
Added by merging #21. Dev builds are available in our discord.
