### ISSUE TITLE
Add additional conditions

### ISSUE THREAD

**Issue by TheQingFengX** [Rosewood-Development/RoseLoot#28]
Existing biomes do not support biomes in Datapack. I'd like to add some conditions that support the structure and biome in the datapack to better set up the chest, similar to MythicMobs'  [structure](https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/skills/conditions/structure) and [biome](https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/skills/conditions/biome) of MythicMobs.. Thank you.

I'm sorry, but I don't speak English.
"The above content is from Microsoft Translator"

**Comment by Esophose** [comment]
You can use the `biome-key` condition for datapack biomes if you are running a Paper server. There is also a `feature` condition you can use to check if the player is within a structure. I don't think any new conditions are needed here so I'm going to close this.
