### ISSUE TITLE
[Some questions] 

### ISSUE THREAD

**Issue by Yurium7** [Rosewood-Development/RoseLoot#29]
Hi Sosewood-Decelopment team
I Have some Qusetions to RoseLoot Plguin

Can this plugin modify the loot in custom datapacks?

**Comment by Esophose** [comment]
It can. Any other questions? You can get a quicker response from our discord server, sorry that took so long though.

**Comment by Yurium7** [comment]
Thank you for your recovery. How should I write a configuration file that can be applied to DataSack?

**Comment by Yurium7** [comment]
感谢您的康复。如何编写可应用于 DataSack 的配置文件？

**Comment by Yurium7** [comment]
> 它可以。还有其他问题吗？您可以从我们的 discord 服务器获得更快的响应，但很抱歉花了这么长时间。

Thank you for your reply. How should I write a configuration file that can be applied to DataSack?
