### ISSUE TITLE
EcoArmor support

### ISSUE THREAD

**Issue by PSYCHEER** [Rosewood-Development/RoseLoot#30]
Hey! I will like to see an EcoArmor support!
Because it does a bit other things as EcoItems.
Thanks.

**Comment by Esophose** [comment]
EcoArmor is already supported as mentioned here https://github.com/Rosewood-Development/RoseLoot/wiki/Custom-Item-Plugins#eco

**Comment by PSYCHEER** [comment]
Sorry, I was answered later on discord too, but already this post existed
