### ISSUE TITLE
EcoBosses? EcoMobs!

### ISSUE THREAD

**Issue by PSYCHEER** [Rosewood-Development/RoseLoot#31]
Hi! I saw in wiki youre still using EcoBosses, but newer version is EcoMobs.
Please update it.

**Comment by Esophose** [comment]
I'll get that updated when I have time, thanks

**Comment by PSYCHEER** [comment]
Thanks

**Comment by Esophose** [comment]
Updated in 3c024fe61b6c10694e5b365a264e74adce2aa772 and released in v1.2.16
