### ISSUE TITLE
Villager trade system

### ISSUE THREAD

**Issue by PSYCHEER** [Rosewood-Development/RoseLoot#32]
Hi! It's possible to add villager trade tables same as piglins?
Would be glad for this!

**Comment by Esophose** [comment]
An open issue for editing villager trades is already open in another GitHub issue and another in our Discord server. I'm going to close this, but will mention I don't currently have plans to add villager trades editing. They don't use loot tables for the trades, and it wouldn't work with how RoseLoot is currently set up and would require an all new set of configs, making it unlikely to ever get added. Other GitHub issue: https://github.com/Rosewood-Development/RoseLoot/issues/6
