### ISSUE TITLE
How to make loot generate in the structure of a packet.

### ISSUE THREAD

**Issue by TheQingFengX** [Rosewood-Development/RoseLoot#33]
I'm planning to add MMoitems to the structure of the packet. But I looked at all the conditions of the plugin and couldn't find one that would make this happen.

Is this something we can do with RoseLoot?

**Comment by Esophose** [comment]
I'm not sure what "the structure of the packet" means, RoseLoot can edit chests from vanilla structures or from datapacks using the CONTAINER type loot table if that's what you mean by structure.

**Comment by TheQingFengX** [comment]
> I'm not sure what "the structure of the packet" means, RoseLoot can edit chests from vanilla structures or from datapacks using the CONTAINER type loot table if that's what you mean by structure.

"the structure of the packet" mean is "the structures created by the data pack"
I want to add items created with MMOItems to the structures generated by the datapack.

My English isn’t very good, so I can only describe things using a translator. I’m very sorry!

**Comment by Esophose** [comment]
That is possible to do using the CONTAINER loot table type. Check the example files within RoseLoot's loottables/examples/vanilla/chests folder for an example of how to overwrite the chest loot table, you just need to replace the vanilla loot table with the one from your datapack in the condition. If you've bought the plugin on Spigot you can join our Discord server for detailed support on how to create the loot table you want.
